db:
  image: postgres
  ports:
    - "5432"

memcached:
  image: memcached
  ports:
    - "11211:11211"

web:
  build: .
  command: bundle exec rails s -p 8080 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "8080:8080"
  links:
    - db
    - memcached
